#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apt'
cookbook 'java', :git =>
'https://github.com/opscode-cookbooks/java'
cookbook 'neo4j-server', :git =>
'http://github.com/sw1nn/neo4j-server-chef-cookbook'
